apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  selector:
    matchLabels:
      app: nodee
  replicas: 1
  template:
    metadata:
      labels:
        app: nodee
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: nginx-container
          image: acrtestting.azurecr.io/acrtestting 
          #          imagePullPolicy: Always
          # imagePullSecrets:
              #      - name: regcred
          env:
          - name: PORT
            value: '3001'
          - name: DB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_URL
          ports:
          - containerPort: 3001
